Data Manipulation and analysis are key tasks in any data science and data analytics project. Pandas provides a wide range of functions for data manipulation and analysis, making it easier to clean, transform and extract insights from data.

In [1]:
import pandas as pd

In [18]:
df = pd.read_csv('sales2.csv')
df.head(5)

,OrderID,OrderDate,Product,Category,Quantity,UnitPrice,City
0,1001,2026-09-27,Headphones,Electronics,1.0,2200.0,Lucknow
1,1002,2026-04-09,Water Bottle,Accessories,NaN,250.0,Mumbai
2,1003,2026-10-05,Headphones,Electronics,5.0,2200.0,NaN
3,1004,2026-10-13,Monitor,Electronics,3.0,NaN,Bengaluru
4,1005,2026-04-21,NaN,Furniture,5.0,6500.0,Pune

In [3]:
df.tail(5)

,OrderID,OrderDate,Product,Category,Quantity,UnitPrice,City
25,1026,2026-02-26,Headphones,Electronics,NaN,2200.0,Delhi
26,1027,2026-08-08,Headphones,Electronics,1.0,2200.0,Chennai
27,1028,2026-02-17,Mouse,Electronics,4.0,NaN,Ahmedabad
28,1029,NaN,Monitor,Electronics,4.0,12000.0,Chennai
29,1030,2026-02-09,Mouse,Electronics,4.0,800.0,Chennai

In [4]:
df.describe()

           OrderID   Quantity     UnitPrice
count    30.000000  26.000000     25.000000
mean   1015.500000   3.115385  10883.600000
std       8.803408   1.451259  17811.293908
min    1001.000000   1.000000    120.000000
25%    1008.250000   2.250000   1500.000000
50%    1015.500000   3.000000   2200.000000
75%    1022.750000   4.000000  12000.000000
max    1030.000000   5.000000  55000.000000

In [5]:
df.dtypes

OrderID        int64
OrderDate     object
Product       object
Category      object
Quantity     float64
UnitPrice    float64
City          object
dtype: object

### Handling Missing Values

In [6]:
df.isnull()

    OrderID  OrderDate  Product  Category  Quantity  UnitPrice   City
0     False      False    False     False     False      False  False
1     False      False    False     False      True      False  False
2     False      False    False     False     False      False   True
3     False      False    False     False     False       True  False
4     False      False     True     False     False      False  False
5     False      False    False     False     False      False  False
6     False       True    False     False     False      False  False
7     False      False    False      True     False      False  False
8     False      False    False     False      True      False  False
9     False      False    False     False     False      False  False
10    False      False    False     False     False       True  False
11    False      False    False     False     False      False   True
12    False      False    False     False     False      False  False
13    False      False    False     False      True      False  False
14    False      False    False     False     False      False  False
15    False      False    False     False     False       True  False
16    False      False    False     False     False      False  False
17    False       True    False     False     False      False  False
18    False      False    False     False     False      False   True
19    False      False    False     False     False      False  False
20    False      False     True     False     False      False  False
21    False      False    False     False     False      False  False
22    False      False    False      True     False      False  False
23    False      False    False     False     False       True  False
24    False      False    False     False     False      False  False
25    False      False    False     False      True      False  False
26    False      False    False     False     False      False  False
27    False      False    False     False     False       True  False
28    False       True    False     False     False      False  False
29    False      False    False     False     False      False  False

In [7]:
df.isnull().any(axis = 1)

0     False
1      True
2      True
3      True
4      True
5     False
6      True
7      True
8      True
9     False
10     True
11     True
12    False
13     True
14    False
15     True
16    False
17     True
18     True
19    False
20     True
21    False
22     True
23     True
24    False
25     True
26    False
27     True
28     True
29    False
dtype: bool

In [13]:
df.isnull().any()

OrderID      False
OrderDate     True
Product       True
Category      True
Quantity      True
UnitPrice    False
City          True
dtype: bool

In [8]:
df.isnull().sum()

OrderID      0
OrderDate    3
Product      2
Category     2
Quantity     4
UnitPrice    5
City         3
dtype: int64

In [9]:
df.isnull().any()

OrderID      False
OrderDate     True
Product       True
Category      True
Quantity      True
UnitPrice     True
City          True
dtype: bool

#### Filling missing values

In [10]:
df.fillna('Not Defined')

,OrderID,OrderDate,Product,Category,Quantity,UnitPrice,City
0,1001,2026-09-27,Headphones,Electronics,1.0,2200.0,Lucknow
1,1002,2026-04-09,Water Bottle,Accessories,Not Defined,250.0,Mumbai
2,1003,2026-10-05,Headphones,Electronics,5.0,2200.0,Not Defined
3,1004,2026-10-13,Monitor,Electronics,3.0,Not Defined,Bengaluru
4,1005,2026-04-21,Not Defined,Furniture,5.0,6500.0,Pune
5,1006,2026-07-09,Notebook Pack,Stationery,5.0,120.0,Hyderabad
6,1007,Not Defined,Headphones,Electronics,5.0,2200.0,Pune
7,1008,2026-11-04,Office Chair,Not Defined,1.0,6500.0,Pune
8,1009,2026-07-18,Mouse,Electronics,Not Defined,800.0,Delhi
9,1010,2026-02-22,Smartphone,Electronics,2.0,30000.0,Jaipur
10,1011,2026-03-23,Notebook Pack,Stationery,3.0,Not Defined,Lucknow
11,1012,2026-06-19,Keyboard,Electronics,3.0,1500.0,Not Defined
12,1013,2026-05-03,Headphones,Electronics,3.0,2200.0,Kolkata
13,1014,2026-02-13,Monitor,Electronics,Not Defined,12000.0,Pune
14,1015,2026-09-19,Laptop,Electronics,3.0,55000.0,Delhi
15,1016,2026-01-12,Headphones,Electronics,3.0,Not Defined,Chennai
16,1017,2026-06-02,Office Chair,Furniture,3.0,6500.0,Bengaluru
17,1018,Not Defined,Laptop,Electronics,1.0,55000.0,Pune
18,1019,2026-05-09,Desk Lamp,Furniture,1.0,1800.0,Not Defined
19,1020,2026-06-04,Laptop,Electronics,3.0,55000.0,Jaipur
20,1021,2026-10-25,Not Defined,Electronics,4.0,2200.0,Ahmedabad
21,1022,2026-02-23,Mouse,Electronics,1.0,800.0,Chennai
22,1023,2026-04-07,Notebook Pack,Not Defined,5.0,120.0,Kolkata
23,1024,2026-04-25,Notebook Pack,Stationery,5.0,Not Defined,Mumbai
24,1025,2026-07-17,Monitor,Electronics,3.0,12000.0,Lucknow
25,1026,2026-02-26,Headphones,Electronics,Not Defined,2200.0,Delhi
26,1027,2026-08-08,Headphones,Electronics,1.0,2200.0,Chennai
27,1028,2026-02-17,Mouse,Electronics,4.0,Not Defined,Ahmedabad
28,1029,Not Defined,Monitor,Electronics,4.0,12000.0,Chennai
29,1030,2026-02-09,Mouse,Electronics,4.0,800.0,Chennai

#### Filling missing values with the mean values of the column

In [ ]:
df['UnitPrice'] = df['UnitPrice'].fillna(df['UnitPrice'].mean())
df

,OrderID,OrderDate,Product,Category,Quantity,UnitPrice,City
0,1001,2026-09-27,Headphones,Electronics,1.0,2200.0,Lucknow
1,1002,2026-04-09,Water Bottle,Accessories,NaN,250.0,Mumbai
2,1003,2026-10-05,Headphones,Electronics,5.0,2200.0,NaN
3,1004,2026-10-13,Monitor,Electronics,3.0,10883.6,Bengaluru
4,1005,2026-04-21,NaN,Furniture,5.0,6500.0,Pune
5,1006,2026-07-09,Notebook Pack,Stationery,5.0,120.0,Hyderabad
6,1007,NaN,Headphones,Electronics,5.0,2200.0,Pune
7,1008,2026-11-04,Office Chair,NaN,1.0,6500.0,Pune
8,1009,2026-07-18,Mouse,Electronics,NaN,800.0,Delhi
9,1010,2026-02-22,Smartphone,Electronics,2.0,30000.0,Jaipur
10,1011,2026-03-23,Notebook Pack,Stationery,3.0,10883.6,Lucknow
11,1012,2026-06-19,Keyboard,Electronics,3.0,1500.0,NaN
12,1013,2026-05-03,Headphones,Electronics,3.0,2200.0,Kolkata
13,1014,2026-02-13,Monitor,Electronics,NaN,12000.0,Pune
14,1015,2026-09-19,Laptop,Electronics,3.0,55000.0,Delhi
15,1016,2026-01-12,Headphones,Electronics,3.0,10883.6,Chennai
16,1017,2026-06-02,Office Chair,Furniture,3.0,6500.0,Bengaluru
17,1018,NaN,Laptop,Electronics,1.0,55000.0,Pune
18,1019,2026-05-09,Desk Lamp,Furniture,1.0,1800.0,NaN
19,1020,2026-06-04,Laptop,Electronics,3.0,55000.0,Jaipur
20,1021,2026-10-25,NaN,Electronics,4.0,2200.0,Ahmedabad
21,1022,2026-02-23,Mouse,Electronics,1.0,800.0,Chennai
22,1023,2026-04-07,Notebook Pack,NaN,5.0,120.0,Kolkata
23,1024,2026-04-25,Notebook Pack,Stationery,5.0,10883.6,Mumbai
24,1025,2026-07-17,Monitor,Electronics,3.0,12000.0,Lucknow
25,1026,2026-02-26,Headphones,Electronics,NaN,2200.0,Delhi
26,1027,2026-08-08,Headphones,Electronics,1.0,2200.0,Chennai
27,1028,2026-02-17,Mouse,Electronics,4.0,10883.6,Ahmedabad
28,1029,NaN,Monitor,Electronics,4.0,12000.0,Chennai
29,1030,2026-02-09,Mouse,Electronics,4.0,800.0,Chennai

### Renaming Columns

In [19]:
df = df.rename(columns={'OrderDate':'Date'})
df.head()

,OrderID,Date,Product,Category,Quantity,UnitPrice,City
0,1001,2026-09-27,Headphones,Electronics,1.0,2200.0,Lucknow
1,1002,2026-04-09,Water Bottle,Accessories,NaN,250.0,Mumbai
2,1003,2026-10-05,Headphones,Electronics,5.0,2200.0,NaN
3,1004,2026-10-13,Monitor,Electronics,3.0,NaN,Bengaluru
4,1005,2026-04-21,NaN,Furniture,5.0,6500.0,Pune

#### Changing Datatypes

In [22]:
df['UnitPrice_new'] = df['UnitPrice'].fillna(df['UnitPrice'].mean()).astype(int)
df.head()

,OrderID,Date,Product,Category,Quantity,UnitPrice,City,UnitPrice_new
0,1001,2026-09-27,Headphones,Electronics,1.0,2200.0,Lucknow,2200
1,1002,2026-04-09,Water Bottle,Accessories,NaN,250.0,Mumbai,250
2,1003,2026-10-05,Headphones,Electronics,5.0,2200.0,NaN,2200
3,1004,2026-10-13,Monitor,Electronics,3.0,NaN,Bengaluru,10883
4,1005,2026-04-21,NaN,Furniture,5.0,6500.0,Pune,6500

### Adding new Column

In [23]:
df['New UnitPrice'] = df['UnitPrice'].apply(lambda x : x * 2)
df.head()

,OrderID,Date,Product,Category,Quantity,UnitPrice,City,UnitPrice_new,New UnitPrice
0,1001,2026-09-27,Headphones,Electronics,1.0,2200.0,Lucknow,2200,4400.0
1,1002,2026-04-09,Water Bottle,Accessories,NaN,250.0,Mumbai,250,500.0
2,1003,2026-10-05,Headphones,Electronics,5.0,2200.0,NaN,2200,4400.0
3,1004,2026-10-13,Monitor,Electronics,3.0,NaN,Bengaluru,10883,NaN
4,1005,2026-04-21,NaN,Furniture,5.0,6500.0,Pune,6500,13000.0

### Data Aggregation and Grouping

In [25]:
grouped_mean = df.groupby('Product')['UnitPrice'].mean()
grouped_mean

Product
Desk Lamp         1800.0
Headphones        2200.0
Keyboard          1500.0
Laptop           55000.0
Monitor          12000.0
Mouse              800.0
Notebook Pack      120.0
Office Chair      6500.0
Smartphone       30000.0
Water Bottle       250.0
Name: UnitPrice, dtype: float64

In [28]:
df.groupby(['Product', 'City'])['UnitPrice'].sum()

Product        City
Headphones     Chennai       2200.0
               Delhi         2200.0
               Kolkata       2200.0
               Lucknow       2200.0
               Pune          2200.0
Laptop         Delhi        55000.0
               Jaipur       55000.0
               Pune         55000.0
Monitor        Bengaluru        0.0
               Chennai      12000.0
               Lucknow      12000.0
               Pune         12000.0
Mouse          Ahmedabad        0.0
               Chennai       1600.0
               Delhi          800.0
Notebook Pack  Hyderabad      120.0
               Kolkata        120.0
               Lucknow          0.0
               Mumbai           0.0
Office Chair   Bengaluru     6500.0
               Pune          6500.0
Smartphone     Jaipur       30000.0
Water Bottle   Mumbai         250.0
Name: UnitPrice, dtype: float64

#### Aggregate Multiple functions

In [31]:
df.groupby('City')['UnitPrice'].agg(['mean', 'sum', 'count'])

                   mean      sum  count
City
Ahmedabad   2200.000000   2200.0      1
Bengaluru   6500.000000   6500.0      1
Chennai     3950.000000  15800.0      4
Delhi      19333.333333  58000.0      3
Hyderabad    120.000000    120.0      1
Jaipur     42500.000000  85000.0      2
Kolkata     1160.000000   2320.0      2
Lucknow     7100.000000  14200.0      2
Mumbai       250.000000    250.0      1
Pune       16440.000000  82200.0      5

#### Merging and Joining DataFrames

##### Creating Sample DataFrames

In [33]:
df1 = pd.DataFrame({'Key' : ['A', 'B', 'C'], 'Value1' : [1, 2, 3]})
df2 = pd.DataFrame({'Key' : ['A', 'B', 'D'], 'Value2' : [4, 5, 6]})

In [34]:
df1

  Key  Value1
0   A       1
1   B       2
2   C       3

In [35]:
df2

  Key  Value2
0   A       4
1   B       5
2   D       6

##### Merge DataFrames on 'Key' Columns

_inner_ join: only common keys will be merged from both DataFrames

In [ ]:
pd.merge(df1, df2, on='Key', how='inner')

  Key  Value1  Value2
0   A       1       4
1   B       2       5

_outer_ join: all keys will be merged from both DataFrames

In [37]:
pd.merge(df1, df2, on='Key', how='outer')

  Key  Value1  Value2
0   A     1.0     4.0
1   B     2.0     5.0
2   C     3.0     NaN
3   D     NaN     6.0

_left_ outer join: first DataFrame will be given more priority in terms of joining, i.e., all keys of left DataFrame will be merged with respect to right Dataframe

In [38]:
pd.merge(df1, df2, on='Key', how='left')

  Key  Value1  Value2
0   A       1     4.0
1   B       2     5.0
2   C       3     NaN

_right_ outer join: second DataFrame will be given more priority in terms of joining, i.e., all keys of right DataFrame will be merged with respect to left Dataframe

In [39]:
pd.merge(df1, df2, on='Key', how='right')

  Key  Value1  Value2
0   A     1.0       4
1   B     2.0       5
2   D     NaN       6