Pandas is a powerful data manipulation library in Python, widely used for data analysis and data cleaning. It provides 2 primary data structures: Series and DataFrame. A Series is a one-dimensional array-like object, while a DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (row and columns)

In [2]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\kiit\desktop\datascience\venv\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\kiit\desktop\datascience\venv\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\kiit\desktop\datascience\venv\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\kiit\desktop\datascience\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\kiit\desktop\datascience\venv\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\kiit\desktop\datascience\venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

### Series
A Pandas Series is a one-dimensional array-like object that can hold any data type. It is similar to column in a table

In [3]:
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print("Series: \n", series)
print(type(series))

Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.core.series.Series'>

#### Create a Series from dictionary

In [ ]:
data = {'a':1, 'b':2, 'c':3, 'd':4, 'e':5}
series_dict = pd.Series(data)
print("Series: \n", series_dict)
print(type(series_dict))

Series:
 a    1
b    2
c    3
d    4
e    5
dtype: int64
<class 'pandas.core.series.Series'>

#### Customized Index

In [5]:
data = [10, 20, 30]
index = ['a', 'b', 'c']
series_ind = pd.Series(data, index = index)
print("Series: \n", series_ind)

Series:
 a    10
b    20
c    30
dtype: int64

### DataFrame
A DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (row and columns)

#### Create a DataFrame from a dictionary of a list

In [4]:
data = {
    'Name' : ['Krish', 'Avneesh', 'John'],
    'Age' : [25, 20, 30],
    'City' : ['Bangalore', 'Noida', 'New York']
}

df = pd.DataFrame(data)
df

      Name  Age       City
0    Krish   25  Bangalore
1  Avneesh   20      Noida
2     John   30   New York

In [5]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

#### Create a DataFrame from a list of dictionaries

In [6]:
data = [
    {'Name' : 'Krish', 'Age' : 25, 'City' : 'Bangalore'},
    {'Name' : 'Avneesh', 'Age' : 20, 'City' : 'Noida'},
    {'Name' : 'John', 'Age' : 30, 'City' : 'New York'}
]

df1 = pd.DataFrame(data)
df1

      Name  Age       City
0    Krish   25  Bangalore
1  Avneesh   20      Noida
2     John   30   New York

In [7]:
print(type(df1))

<class 'pandas.core.frame.DataFrame'>

In [8]:
data = [
    {'Name' : 'Krish', 'Age' : 25, 'City' : 'Bangalore'},
    {'Name' : 'Avneesh', 'Age' : 20, 'City' : 'Noida', 'Pincode' : 201306},
    {'Name' : 'John', 'Age' : 30, 'City' : 'New York'}
]

df2 = pd.DataFrame(data)
df2

      Name  Age       City   Pincode
0    Krish   25  Bangalore       NaN
1  Avneesh   20      Noida  201306.0
2     John   30   New York       NaN

In [9]:
print(type(df2))

<class 'pandas.core.frame.DataFrame'>

#### Reading a CSV file

In [10]:
df = pd.read_csv('sales_data.csv')
df.head(5)

,OrderID,OrderDate,Product,Category,Quantity,UnitPrice,City
0,1001,2026-09-27,Headphones,Electronics,1,2200,Lucknow
1,1002,2026-04-09,Water Bottle,Accessories,5,250,Mumbai
2,1003,2026-10-05,Headphones,Electronics,5,2200,Pune
3,1004,2026-10-13,Monitor,Electronics,3,12000,Bengaluru
4,1005,2026-04-21,Office Chair,Furniture,5,6500,Pune

In [11]:
df.tail(5)

,OrderID,OrderDate,Product,Category,Quantity,UnitPrice,City
95,1096,2026-05-19,Keyboard,Electronics,2,1500,Jaipur
96,1097,2026-06-08,Monitor,Electronics,2,12000,Pune
97,1098,2026-03-07,Monitor,Electronics,5,12000,Chennai
98,1099,2026-07-26,Water Bottle,Accessories,3,250,Bengaluru
99,1100,2026-10-26,Smartphone,Electronics,1,30000,Hyderabad

#### Accessing data from DataFrame

In [12]:
df

,OrderID,OrderDate,Product,Category,Quantity,UnitPrice,City
0,1001,2026-09-27,Headphones,Electronics,1,2200,Lucknow
1,1002,2026-04-09,Water Bottle,Accessories,5,250,Mumbai
2,1003,2026-10-05,Headphones,Electronics,5,2200,Pune
3,1004,2026-10-13,Monitor,Electronics,3,12000,Bengaluru
4,1005,2026-04-21,Office Chair,Furniture,5,6500,Pune
...,...,...,...,...,...,...,...
95,1096,2026-05-19,Keyboard,Electronics,2,1500,Jaipur
96,1097,2026-06-08,Monitor,Electronics,2,12000,Pune
97,1098,2026-03-07,Monitor,Electronics,5,12000,Chennai
98,1099,2026-07-26,Water Bottle,Accessories,3,250,Bengaluru
99,1100,2026-10-26,Smartphone,Electronics,1,30000,Hyderabad

In [13]:
print(df['Product'], "\n")
print(type(df['Product']))

0       Headphones
1     Water Bottle
2       Headphones
3          Monitor
4     Office Chair
          ...
95        Keyboard
96         Monitor
97         Monitor
98    Water Bottle
99      Smartphone
Name: Product, Length: 100, dtype: object

<class 'pandas.core.series.Series'>

In [14]:
df.loc[0]

OrderID             1001
OrderDate     2026-09-27
Product       Headphones
Category     Electronics
Quantity               1
UnitPrice           2200
City             Lucknow
Name: 0, dtype: object

In [14]:
df.iloc[0][1]

C:\Users\KIIT\AppData\Local\Temp\ipykernel_13512\2309508539.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df.iloc[0][1]

'2026-09-27'

#### Accessing a Specified Element

In [15]:
df.at[1, 'OrderDate']

'2026-04-09'

In [16]:
df

,OrderID,OrderDate,Product,Category,Quantity,UnitPrice,City
0,1001,2026-09-27,Headphones,Electronics,1,2200,Lucknow
1,1002,2026-04-09,Water Bottle,Accessories,5,250,Mumbai
2,1003,2026-10-05,Headphones,Electronics,5,2200,Pune
3,1004,2026-10-13,Monitor,Electronics,3,12000,Bengaluru
4,1005,2026-04-21,Office Chair,Furniture,5,6500,Pune
...,...,...,...,...,...,...,...
95,1096,2026-05-19,Keyboard,Electronics,2,1500,Jaipur
96,1097,2026-06-08,Monitor,Electronics,2,12000,Pune
97,1098,2026-03-07,Monitor,Electronics,5,12000,Chennai
98,1099,2026-07-26,Water Bottle,Accessories,3,250,Bengaluru
99,1100,2026-10-26,Smartphone,Electronics,1,30000,Hyderabad

In [17]:
df.at[11, 'Product']

'Keyboard'

#### Accessing a specified element using iat

In [18]:
df.iat[11, 2]

'Keyboard'

#### Data Manipulation with DataFrame

#####     Adding A Column

In [19]:
df['TotalAmount'] = df['Quantity'] * df['UnitPrice']
df

,OrderID,OrderDate,Product,Category,Quantity,UnitPrice,City,TotalAmount
0,1001,2026-09-27,Headphones,Electronics,1,2200,Lucknow,2200
1,1002,2026-04-09,Water Bottle,Accessories,5,250,Mumbai,1250
2,1003,2026-10-05,Headphones,Electronics,5,2200,Pune,11000
3,1004,2026-10-13,Monitor,Electronics,3,12000,Bengaluru,36000
4,1005,2026-04-21,Office Chair,Furniture,5,6500,Pune,32500
...,...,...,...,...,...,...,...,...
95,1096,2026-05-19,Keyboard,Electronics,2,1500,Jaipur,3000
96,1097,2026-06-08,Monitor,Electronics,2,12000,Pune,24000
97,1098,2026-03-07,Monitor,Electronics,5,12000,Chennai,60000
98,1099,2026-07-26,Water Bottle,Accessories,3,250,Bengaluru,750
99,1100,2026-10-26,Smartphone,Electronics,1,30000,Hyderabad,30000

##### Removing A Column

In [24]:
df.drop('TotalAmount', axis = 1)

,OrderID,OrderDate,Product,Category,Quantity,UnitPrice,City
0,1001,2026-09-27,Headphones,Electronics,1,2200,Lucknow
1,1002,2026-04-09,Water Bottle,Accessories,5,250,Mumbai
2,1003,2026-10-05,Headphones,Electronics,5,2200,Pune
3,1004,2026-10-13,Monitor,Electronics,3,12000,Bengaluru
4,1005,2026-04-21,Office Chair,Furniture,5,6500,Pune
...,...,...,...,...,...,...,...
95,1096,2026-05-19,Keyboard,Electronics,2,1500,Jaipur
96,1097,2026-06-08,Monitor,Electronics,2,12000,Pune
97,1098,2026-03-07,Monitor,Electronics,5,12000,Chennai
98,1099,2026-07-26,Water Bottle,Accessories,3,250,Bengaluru
99,1100,2026-10-26,Smartphone,Electronics,1,30000,Hyderabad

_Temporary Deletion of Column using only axis. From above it can be seen that the column is dropped but after printing csv again it appears once again._

In [25]:
df

,OrderID,OrderDate,Product,Category,Quantity,UnitPrice,City,TotalAmount
0,1001,2026-09-27,Headphones,Electronics,1,2200,Lucknow,2200
1,1002,2026-04-09,Water Bottle,Accessories,5,250,Mumbai,1250
2,1003,2026-10-05,Headphones,Electronics,5,2200,Pune,11000
3,1004,2026-10-13,Monitor,Electronics,3,12000,Bengaluru,36000
4,1005,2026-04-21,Office Chair,Furniture,5,6500,Pune,32500
...,...,...,...,...,...,...,...,...
95,1096,2026-05-19,Keyboard,Electronics,2,1500,Jaipur,3000
96,1097,2026-06-08,Monitor,Electronics,2,12000,Pune,24000
97,1098,2026-03-07,Monitor,Electronics,5,12000,Chennai,60000
98,1099,2026-07-26,Water Bottle,Accessories,3,250,Bengaluru,750
99,1100,2026-10-26,Smartphone,Electronics,1,30000,Hyderabad,30000

Solution: _Use inplace = True for permanent deletion_

In [26]:
df.drop('TotalAmount', axis = 1, inplace=True)

In [27]:
df

,OrderID,OrderDate,Product,Category,Quantity,UnitPrice,City
0,1001,2026-09-27,Headphones,Electronics,1,2200,Lucknow
1,1002,2026-04-09,Water Bottle,Accessories,5,250,Mumbai
2,1003,2026-10-05,Headphones,Electronics,5,2200,Pune
3,1004,2026-10-13,Monitor,Electronics,3,12000,Bengaluru
4,1005,2026-04-21,Office Chair,Furniture,5,6500,Pune
...,...,...,...,...,...,...,...
95,1096,2026-05-19,Keyboard,Electronics,2,1500,Jaipur
96,1097,2026-06-08,Monitor,Electronics,2,12000,Pune
97,1098,2026-03-07,Monitor,Electronics,5,12000,Chennai
98,1099,2026-07-26,Water Bottle,Accessories,3,250,Bengaluru
99,1100,2026-10-26,Smartphone,Electronics,1,30000,Hyderabad

In [ ]:
df['Quantity'] = df['Quantity'] + 1

In [29]:
df

,OrderID,OrderDate,Product,Category,Quantity,UnitPrice,City
0,1001,2026-09-27,Headphones,Electronics,2,2200,Lucknow
1,1002,2026-04-09,Water Bottle,Accessories,6,250,Mumbai
2,1003,2026-10-05,Headphones,Electronics,6,2200,Pune
3,1004,2026-10-13,Monitor,Electronics,4,12000,Bengaluru
4,1005,2026-04-21,Office Chair,Furniture,6,6500,Pune
...,...,...,...,...,...,...,...
95,1096,2026-05-19,Keyboard,Electronics,3,1500,Jaipur
96,1097,2026-06-08,Monitor,Electronics,3,12000,Pune
97,1098,2026-03-07,Monitor,Electronics,6,12000,Chennai
98,1099,2026-07-26,Water Bottle,Accessories,4,250,Bengaluru
99,1100,2026-10-26,Smartphone,Electronics,2,30000,Hyderabad

#### Removing a row

In [30]:
df.drop(0)

,OrderID,OrderDate,Product,Category,Quantity,UnitPrice,City
1,1002,2026-04-09,Water Bottle,Accessories,6,250,Mumbai
2,1003,2026-10-05,Headphones,Electronics,6,2200,Pune
3,1004,2026-10-13,Monitor,Electronics,4,12000,Bengaluru
4,1005,2026-04-21,Office Chair,Furniture,6,6500,Pune
5,1006,2026-07-09,Notebook Pack,Stationery,6,120,Hyderabad
...,...,...,...,...,...,...,...
95,1096,2026-05-19,Keyboard,Electronics,3,1500,Jaipur
96,1097,2026-06-08,Monitor,Electronics,3,12000,Pune
97,1098,2026-03-07,Monitor,Electronics,6,12000,Chennai
98,1099,2026-07-26,Water Bottle,Accessories,4,250,Bengaluru
99,1100,2026-10-26,Smartphone,Electronics,2,30000,Hyderabad

In [31]:
df

,OrderID,OrderDate,Product,Category,Quantity,UnitPrice,City
0,1001,2026-09-27,Headphones,Electronics,2,2200,Lucknow
1,1002,2026-04-09,Water Bottle,Accessories,6,250,Mumbai
2,1003,2026-10-05,Headphones,Electronics,6,2200,Pune
3,1004,2026-10-13,Monitor,Electronics,4,12000,Bengaluru
4,1005,2026-04-21,Office Chair,Furniture,6,6500,Pune
...,...,...,...,...,...,...,...
95,1096,2026-05-19,Keyboard,Electronics,3,1500,Jaipur
96,1097,2026-06-08,Monitor,Electronics,3,12000,Pune
97,1098,2026-03-07,Monitor,Electronics,6,12000,Chennai
98,1099,2026-07-26,Water Bottle,Accessories,4,250,Bengaluru
99,1100,2026-10-26,Smartphone,Electronics,2,30000,Hyderabad

_Permanent Deletion_

In [32]:
df.drop(0, inplace=True)

In [33]:
df

,OrderID,OrderDate,Product,Category,Quantity,UnitPrice,City
1,1002,2026-04-09,Water Bottle,Accessories,6,250,Mumbai
2,1003,2026-10-05,Headphones,Electronics,6,2200,Pune
3,1004,2026-10-13,Monitor,Electronics,4,12000,Bengaluru
4,1005,2026-04-21,Office Chair,Furniture,6,6500,Pune
5,1006,2026-07-09,Notebook Pack,Stationery,6,120,Hyderabad
...,...,...,...,...,...,...,...
95,1096,2026-05-19,Keyboard,Electronics,3,1500,Jaipur
96,1097,2026-06-08,Monitor,Electronics,3,12000,Pune
97,1098,2026-03-07,Monitor,Electronics,6,12000,Chennai
98,1099,2026-07-26,Water Bottle,Accessories,4,250,Bengaluru
99,1100,2026-10-26,Smartphone,Electronics,2,30000,Hyderabad

### Extras

#### Display the datatypes for each column

In [34]:
print("Data Types:\n", df.dtypes)

Data Types:
 OrderID       int64
OrderDate    object
Product      object
Category     object
Quantity      int64
UnitPrice     int64
City         object
dtype: object

#### Describe the DataFrame

In [38]:
df.describe()

           OrderID   Quantity     UnitPrice
count    99.000000  99.000000     99.000000
mean   1051.000000   3.959596   9736.666667
std      28.722813   1.331864  15588.413738
min    1002.000000   2.000000    120.000000
25%    1026.500000   3.000000    800.000000
50%    1051.000000   4.000000   2200.000000
75%    1075.500000   5.000000  12000.000000
max    1100.000000   6.000000  55000.000000

#### Group by a column and perform an aggregation

In [37]:
grouped = df.groupby('Product')['UnitPrice'].mean()
print("Mean value by category:\n", grouped)

Mean value by category:
 Product
Desk Lamp         1800.0
Headphones        2200.0
Keyboard          1500.0
Laptop           55000.0
Monitor          12000.0
Mouse              800.0
Notebook Pack      120.0
Office Chair      6500.0
Smartphone       30000.0
Water Bottle       250.0
Name: UnitPrice, dtype: float64